In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /home/mora/anaconda3/lib/python3.8/site-packages (8.0.28)
Requirement already satisfied: protobuf>=3.0.0 in /home/mora/anaconda3/lib/python3.8/site-packages (from mysql-connector-python) (3.19.4)

In [2]:
import mysql.connector as conn
import pandas as pd

In [3]:
crea_db=conn.connect(host='localhost',
                     user='root',
                     passwd='admin')

cursor=crea_db.cursor()

cursor.execute('drop database if exists productos')
cursor.execute('create database productos')

In [4]:
cursor.execute('show databases')

for x in cursor:
    print(x)

('information_schema',)
('mydb',)
('mysql',)
('performance_schema',)
('productos',)
('pubs',)
('sys',)

In [5]:
db=conn.connect(host='localhost',
                     user='root',
                     passwd='admin',
                     database='pubs')
cursor=db.cursor()

In [6]:
cursor.execute('show tables')
for x in cursor:
    print (x)

('authors',)
('discounts',)
('employee',)
('jobs',)
('pub_info',)
('publishers',)
('roysched',)
('sales',)
('stores',)
('titleauthor',)
('titles',)

In [7]:
cursor.execute(             
               '''create temporary table pubs.royalty
               SELECT  a.au_id AS "AUTHOR ID",  
               tl.price AS "price",   
               tl.title AS "Title",
               tl.price * sa.qty * tl.royalty / 100 * ta.royaltyper / 100 AS "royal_sales"
               FROM authors AS a
               LEFT JOIN titleauthor AS ta ON a.au_id = ta.au_id
               LEFT JOIN titles AS tl ON tl.title_id = ta.title_id
               LEFT JOIN publishers AS pb ON pb.pub_id = tl.pub_id
               LEFT JOIN sales AS sa ON sa.title_id = ta.title_id
               order by 'royal_sales' desc;''')

In [8]:
pd.read_sql('''select* from royalty''',db)

,AUTHOR ID,price,Title,royal_sales
0,172-32-1176,19.99,Prolonged Data Deprivation: Four Case Studies,29.985
1,213-46-8915,19.99,The Busy Executive's Database Guide,3.998
2,213-46-8915,19.99,The Busy Executive's Database Guide,7.996
3,213-46-8915,2.99,You Can Combat Computer Stress!,25.116
4,238-95-7766,22.95,But Is It User Friendly?,110.160
5,267-41-2394,11.95,Cooking with Computers: Surreptitious Balance ...,11.950
6,267-41-2394,14.99,"Sushi, Anyone?",8.994
7,274-80-9391,19.99,Straight Talk About Computers,29.985
8,341-22-1782,NaN,None,NaN
9,409-56-7008,19.99,The Busy Executive's Database Guide,5.997
10,409-56-7008,19.99,The Busy Executive's Database Guide,11.994
11,427-17-2319,20.00,Secrets of Silicon Valley,50.000
12,472-27-2349,14.99,"Sushi, Anyone?",8.994
13,486-29-1786,NaN,Net Etiquette,NaN
14,486-29-1786,7.99,Emotional Security: A New Algorithm,19.975
15,527-72-3246,NaN,None,NaN
16,648-92-1872,11.95,Fifty Years in Buckingham Palace Kitchens,33.460
17,672-71-3249,14.99,"Sushi, Anyone?",11.992
18,712-45-1867,19.99,Silicon Valley Gastronomic Treats,23.988
19,722-51-5454,2.99,The Gourmet Microwave,13.455
20,722-51-5454,2.99,The Gourmet Microwave,8.073
21,724-08-9931,NaN,None,NaN
22,724-80-9391,11.95,Cooking with Computers: Surreptitious Balance ...,17.925
23,724-80-9391,21.59,Computer Phobic AND Non-Phobic Individuals: Be...,10.795
24,756-30-7391,21.59,Computer Phobic AND Non-Phobic Individuals: Be...,32.385
25,807-91-6654,20.95,"Onions, Leeks, and Garlic: Cooking Secrets of ...",83.800
26,846-92-7186,20.00,Secrets of Silicon Valley,50.000
27,893-72-1158,NaN,None,NaN
28,899-46-2035,2.99,The Gourmet Microwave,4.485
29,899-46-2035,2.99,The Gourmet Microwave,2.691
30,899-46-2035,10.95,Is Anger the Enemy?,1.971
31,899-46-2035,10.95,Is Anger the Enemy?,49.275
32,899-46-2035,10.95,Is Anger the Enemy?,6.570
33,899-46-2035,10.95,Is Anger the Enemy?,13.140
34,998-72-3567,10.95,Is Anger the Enemy?,1.971
35,998-72-3567,10.95,Is Anger the Enemy?,49.275
36,998-72-3567,10.95,Is Anger the Enemy?,6.570
37,998-72-3567,10.95,Is Anger the Enemy?,13.140
38,998-72-3567,7.00,Life Without Fear,17.500

In [9]:
cursor.execute('''create temporary table pubs.royaltyauthor
                SELECT  a.au_id AS "AUTHOR ID", 
                tl.price AS "price",   
                tl.title AS "Title",
                sum(tl.price * sa.qty * tl.royalty / 100 * ta.royaltyper / 100) AS "royal_sales"
                FROM authors AS a
                LEFT JOIN titleauthor AS ta ON a.au_id = ta.au_id  
                LEFT JOIN titles AS tl ON tl.title_id = ta.title_id
                LEFT JOIN publishers AS pb ON pb.pub_id = tl.pub_id 
                LEFT JOIN sales AS sa ON sa.title_id = ta.title_id
                group by tl.title;''')

In [10]:
pd.read_sql('''select* from royaltyauthor''',db)

,AUTHOR ID,price,Title,royal_sales
0,172-32-1176,19.99,Prolonged Data Deprivation: Four Case Studies,29.985
1,213-46-8915,19.99,The Busy Executive's Database Guide,29.985
2,213-46-8915,2.99,You Can Combat Computer Stress!,25.116
3,238-95-7766,22.95,But Is It User Friendly?,110.160
4,267-41-2394,11.95,Cooking with Computers: Surreptitious Balance ...,29.875
5,267-41-2394,14.99,"Sushi, Anyone?",29.980
6,274-80-9391,19.99,Straight Talk About Computers,29.985
7,341-22-1782,NaN,None,NaN
8,427-17-2319,20.00,Secrets of Silicon Valley,100.000
9,486-29-1786,NaN,Net Etiquette,NaN
10,486-29-1786,7.99,Emotional Security: A New Algorithm,19.975
11,648-92-1872,11.95,Fifty Years in Buckingham Palace Kitchens,33.460
12,712-45-1867,19.99,Silicon Valley Gastronomic Treats,23.988
13,722-51-5454,2.99,The Gourmet Microwave,28.704
14,724-80-9391,21.59,Computer Phobic AND Non-Phobic Individuals: Be...,43.180
15,807-91-6654,20.95,"Onions, Leeks, and Garlic: Cooking Secrets of ...",83.800
16,899-46-2035,10.95,Is Anger the Enemy?,141.912
17,998-72-3567,7.00,Life Without Fear,17.500

In [11]:
cursor.execute('''create temporary table pubs.royalfroupsauthottitles
                Select * from
                    (SELECT  a.au_id AS "AUTHOR ID", 
                    tl.price AS "price",   
                    tl.title AS "Title",
                    sum(tl.price * sa.qty * tl.royalty / 100 * ta.royaltyper / 100) AS "royal_sales"
                    FROM authors AS a
                    LEFT JOIN titleauthor AS ta ON a.au_id = ta.au_id  
                    LEFT JOIN titles AS tl ON tl.title_id = ta.title_id
                    LEFT JOIN publishers AS pb ON pb.pub_id = tl.pub_id 
                    LEFT JOIN sales AS sa ON sa.title_id = ta.title_id
                    group by a.au_id) as tabla
                group by Title;''')

In [12]:
pd.read_sql('''select* from royalfroupsauthottitles''',db)

,AUTHOR ID,price,Title,royal_sales
0,172-32-1176,19.99,Prolonged Data Deprivation: Four Case Studies,29.985
1,213-46-8915,19.99,The Busy Executive's Database Guide,37.110
2,238-95-7766,22.95,But Is It User Friendly?,110.160
3,267-41-2394,11.95,Cooking with Computers: Surreptitious Balance ...,20.944
4,274-80-9391,19.99,Straight Talk About Computers,29.985
5,341-22-1782,NaN,None,NaN
6,427-17-2319,20.00,Secrets of Silicon Valley,50.000
7,472-27-2349,14.99,"Sushi, Anyone?",8.994
8,486-29-1786,NaN,Net Etiquette,19.975
9,648-92-1872,11.95,Fifty Years in Buckingham Palace Kitchens,33.460
10,712-45-1867,19.99,Silicon Valley Gastronomic Treats,23.988
11,722-51-5454,2.99,The Gourmet Microwave,21.528
12,756-30-7391,21.59,Computer Phobic AND Non-Phobic Individuals: Be...,32.385
13,807-91-6654,20.95,"Onions, Leeks, and Garlic: Cooking Secrets of ...",83.800
14,998-72-3567,10.95,Is Anger the Enemy?,88.456